config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'home#index', as: 'welcome'
  resources :users
  resources :expenses, except: %i[index new create]
  resources :categories, only: %i[index new create] do
    resources :expenses, only: %i[index new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_and_belongs_to_many :expenses, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3 }
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_and_belongs_to_many :categories, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  after_save :update_category_total_amount
  before_destroy :reduce_category_total_amount

  private

  def update_category_total_amount
    categories.each do |category|
      category.increment!(:total_amount, amount)
    end
  end

  def reduce_category_total_amount
    categories.each do |category|
      category.decrement!(:total_amount, amount)
    end
  end
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    return if value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

    record.errors.add attribute, (options[:message] || 'is not an email')
  end
end

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses, dependent: :destroy
  has_many :categories, dependent: :destroy
  validates :name, presence: true, length: { in: 3..25 }
  validates :email, presence: true, uniqueness: true, email: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end

  def after_sign_out_path_for(_resource_or_scope)
    welcome_path
  end

  def after_sign_in_path_for(_resource_or_scope)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(name: category_params[:name], icon: category_params[:icon], author: current_user)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json

  private

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]

  # GET /expenses or /expenses.json
  def index
    @category = Category.find(params[:category_id])
    @expenses = @category.expenses.order(created_at: :desc)
  end

  # GET /expenses/new
  def new
    @category = Category.find(params[:category_id])
    @expense = Expense.new
  end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(name: expense_params[:name],
                           amount: expense_params[:amount],
                           author: current_user)
    expense_params[:category_ids].each do |item|
      @expense.categories << Category.find(item) if item != ''
    end
    # p @expense
    respond_to do |format|
      if @expense.save
        format.html do
          redirect_to category_expenses_url(params[:category_id]), notice: 'Expense was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: [])
    # params.require(:wiki).permit(collaborating_user_ids: [], ...)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'splash'
  before_action :authenticate_user!, except: [:index]
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="d-flex flex-row card border-1 mt-2 mx-1 py-2 px-1 shadow">
  <div class="d-flex flex-column flex-grow-1 justify-content-between">
    <div>
      <strong>Name:</strong>
      <%= category.name %>
    </div>
    <div>
      <strong>Total Amount:</strong>
      $<%= category.total_amount %>
    </div>
  </div>
  <div class="w-25 h-25">
    <%= image_tag(category.icon, class: "w-100") %>
  </div>
  <%= link_to '', category_expenses_path(category), id: "category-#{category.id}",  class: 'stretched-link' %>
</div>

app/views/categories/_form.html.erb
<div class=" text-center">
<%= form_with(model: category, html: {id: 'new-category'} ) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class: 'visually-hidden' %>
    <%= form.text_field :name, class: 'w-100  form-control rounded-0', placeholder: 'Name'  %>
  </div>

  <div>
    <%= form.label :icon, class: 'visually-hidden' %>
    <%= form.text_field :icon, class: 'w-100  form-control rounded-0', placeholder: 'Icon Url'  %>
  </div>
<% end %>
</div>

app/views/categories/index.html.erb
<%= render 'partials/header', back_label: '< Logout', back_link: destroy_user_session_path, destroy: 'session', header: 'Categories' %>
<div class="mb-5">
  <div id="categories">
    <% @categories.each do |category| %>
      <%= render category %>
    <% end %>
  </div>
  <%= link_to "Add category", new_category_path, class: 'fixed-bottom bg-white app-text text-decoration-none shadow btn text-center border-top' %>
</div>

app/views/categories/new.html.erb
<%= render 'partials/header', back_label: '<Back', back_link: categories_path, header: 'New category', action: 'Add>' %>
<%= render "form", category: @category %>

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>" class="card mt-2 mx-1 p-2 shadow-sm">
  <div class="d-flex flex-row justify-content-between">
    <h3><%= expense.name %></h3>
    <div class="h5">$<%= expense.amount %></div>
  </div>
  <div><%= expense.created_at.strftime("%B %-d, %Y") %></div>
</div>

app/views/expenses/_form.html.erb
<div class=" text-center">
  <%= form_with(model: expense, url: category_expenses_path(params[:category_id]), html: { id: 'new-transaction' }) do |form| %>
    <% if expense.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

        <ul>
          <% expense.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.label :name, class: 'form-label visually-hidden' %>
      <%= form.text_field :name, class: 'w-100  form-control rounded-0', placeholder: 'Name' %>
    </div>
    <div class="form-group">
      <%= form.label :amount, class: 'form-label visually-hidden' %>
      <%= form.number_field :amount, class: 'w-100  form-control rounded-0', placeholder: 'Amount' %>
    </div>
    <div class="form-group text-start p-2">
      <%= form.label :Categories, class: 'form-label h5' %> <br/>
      <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
        <div class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/expenses/index.html.erb
<%= render 'partials/header', back_label: '< Back', back_link: categories_path, header: 'Transactions', next_value: "$#{@category.total_amount}" %>
<div id="expenses" class="mb-5">
  <% @expenses.each do |expense| %>
    <%= render expense %>
  <% end %>
</div>
<%= link_to "Add Transaction", new_category_expense_path(@category), class: 'fixed-bottom bg-white app-text text-decoration-none shadow btn text-center border-top'  %>

app/views/expenses/new.html.erb
<%= render 'partials/header', back_label: '<Back', back_link: category_expenses_path(params[:category_id]), header: 'New Transactions', action: 'Add>' %>
<%= render "form", expense: @expense %>

app/views/home/index.html.erb
<div class="d-flex flex-column h-100 py-5  text-center px-2">
  <div class="flex-grow-1 d-flex flex-column flex-center">
    <h1 class="my-auto">
      <img src="https://i.ibb.co/pZb9kHv/expenses.png" class="w-25">
    </h1>
  </div>
  <div class="d-flex flex-column gap-2">
    <%= link_to 'Login', new_user_session_path, class: 'btn btn-color-primary py-2 rounded-0' %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-light py-2 rounded-0' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budget App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<div class="vh-100 mt-6">
  <div class="container m-0 p-0">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger text-success"><%= alert %></p>
    <% end %>
  </div>
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budget App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<div class="vh-100">
  <%= yield %>
</div>
</body>
</html>

app/views/partials/_header.html.erb
<div class="fixed-top d-flex bg-color-primary py-2 text-center text-white">
  <% if local_variables.include?(:destroy) %>
    <div><%= button_to back_label, back_link, class: 'btn text-white text-decoration-none', method: :delete %></div>
  <% else %>
    <div><%= link_to back_label, back_link, class: 'btn text-white text-decoration-none' %></div>
  <% end %>
  <h2 class="flex-grow-1 pt-1"><%= header %></h2>
  <% if local_variables.include?(:next_value) %>
    <div class="btn text-white"><%= next_value %></div>
  <% elsif local_variables.include?(:action) %>
    <button id="process-form" class="btn border-0 text-white"><%= action %></button>
  <% end %>
</div>